## **Die %autosave Zelle unbedingt ausführen!**

In [1]:
%autosave 10

Autosaving every 10 seconds


## 19. Abschließende Aufgaben
Heute wiederholen wir mit Aufgaben den Stoff der letzten Tage. \
Das heißt wir Mentoren reden weniger, und ihr programmiert dafür mehr :)

In [16]:
## Aufgabe 1: Strings, Pangrams
# Überarbeitet aus:
# Übungsblatt 2, Programmieren - Sommersemester 2025, Karlsruher Institut für Technologie (KIT)

# Schreibe eine Methode isPangram(sentence), die überprüft,
# ob ein Satz alle Buchstaben des englischen Alphabets (a–z) mindestens einmal enthält. Die
# Groß- und Kleinschreibung soll dabei ignoriert werden. Die Methode gibt True zurück, wenn
# es sich um ein Pangram handelt, andernfalls False.
abc = "abcdefghijklmnopqrstuvwxyz"

def isPangram(sentence):
    sentence = sentence.lower()
    has_all = True
    for char in abc:
        has_all = has_all and (char in sentence)
    return has_all

print(isPangram("This is not a pangram.")) # False
print(isPangram("Pack my box with five dozen liquor jugs.")) # True

False
True


In [8]:
## Aufgabe 2: Listen und Integers, Gefilterte Liste
# Überarbeitet aus:
# Übungsblatt 2, Programmieren - Sommersemester 2025, Karlsruher Institut für Technologie (KIT)

# Schreibe eine Methode greaterThan(values, threshold),
# welche alle Werte in der gegebenen values-Liste in einer neuen int-Liste zurückgibt, die echt
# größer als der gegebene threshold-Wert sind.

def greaterThan(values, threshold):
    result = []
    for element in values:
        if element >= threshold:
            result.append(element)
    return result

print(greaterThan([-5, 0, 5], 0))

[0, 5]


In [9]:
## Aufgabe 3: Listen und Integer, Überschneidungen
# Überarbeitet aus:
# Übungsblatt 2, Programmieren - Sommersemester 2025, Karlsruher Institut für Technologie (KIT)

# Schreibe eine Methode areDisjoint(first, second),
# welche überprüft, ob die beiden gegebenen Listen first und second keine gemeinsamen
# Elemente enthalten. Gib True zurück, wenn es keine Überschneidung gibt, sonst False.

def areDisjoint(first, second):
    for element1 in first:
        if element1 in second:
            return False
    return True

print(areDisjoint([3, 1, 4], [2, 5, 6]))
print(areDisjoint([3, 1, 4], [2, 4, 6]))

True
False


In [31]:
## Aufgabe 4: Dictionaries
# Schreibe eine Methode mergeDictionaries(first, second),
# welche ein neues Dictionary erstellt, das alle Key-Value-Paare
# aus first und second enthält.
# Falls ein key in beiden Dictionaries Werten vorkommt, gebe ein leeres Dictionary zurück.

def mergeDictionaries(first, second):
    result = {}
    for key, value in first.items():
        result[key] = value
    for key, value in second.items():
        if key in result.keys(): 
            return {}
        result[key] = value
    return result

print(mergeDictionaries({"Deutschland": 84, "China": 1419}, {"Mali": 24, "Ukraine": 38}))
print(mergeDictionaries({"Deutschland": 84, "China": 1419}, {"Deutschland": 42, "Mali": 24, "Ukraine": 38})) # {}

{'Deutschland': 84, 'China': 1419, 'Mali': 24, 'Ukraine': 38}
{}


In [23]:
## Aufgabe 5: OOP, Abenteuerspiel, Zeitaufwand nach oben offen ;)
# Überarbeitet aus:
# Übungsblatt 2, Programmieren - Sommersemester 2025, Karlsruher Institut für Technologie (KIT)

# Der Aufgabentext ist ziemlich lang, deswegen ist er weiter unten.

# Ihr werdet vermutlich nicht mit allem fertig werden, aber das ist okay.
# Wenn ihr Spaß dran habt, könnt ihr immer weiter dran arbeiten :)

**Tipp: In dieser Aufgabe werden *enums* sehr praktisch sein.** \
Enums (kurz für enumerations, also Aufzählungen) sind eine Menge von Namen,
die an Werte gebunden sind und im Code verwendet werden können. 
Enums sind in Python ein Spezialfall von Klassen, die keine Methoden haben. \
Anders als Variablen sind diese allerdings konstant. Hier ein Beispiel:
```
from enum import Enum

class Weekday(Enum):
    MONDAY = 1
    TUESDAY = 2
    WEDNESDAY = 3
    THURSDAY = 4
    FRIDAY = 5
    SATURDAY = 6
    SUNDAY = 7
    
print(Weekday.THURSDAY) # -> 4
```

**Und jetzt zur Aufgabe:**
In dieser Aufgabe sollen die grundlegenden Klassen für ein Abenteuerspiel modelliert werden. \
Das primäre Ziel ist es, sich mit dem Entwurf und Erstellen von Klassen in Python vertraut zu
machen. Darüber hinaus sollt ihr das Hinzufügen von Attributen zu Klassen üben.
Es geht hierbei um die reine objektorientierte Modellierung der Klassen und ihrer Attribute. 
Das heißt, eure Klassen beinhalten noch keine Methoden.

**Spiel** Das Spiel besitzt einen Titel und eine kurze Beschreibung. Es besteht aus mehreren Leveln,
die nacheinander durchlaufen werden. Außerdem gibt es eine Liste aller Spieler, die im Spiel
registriert sind.

**Level** Jedes Level hat eine eindeutige Nummer, einen Namen, eine Schwierigkeitsstufe sowie
einen Beschreibungstext, der das Ziel des Levels erklärt. Es gehört eine Karte dazu, die das
Layout definiert. Außerdem enthält das Level verschiedene Gegner und Gegenstände, die dort
vorkommen.

**Karte** Die Karte eines Levels beschreibt das Layout. Sie hat eine bestimmte Breite und Höhe
(jeweils in Kacheln angegeben).

**Spieler** Jeder Spieler hat einen Nutzernamen, einen sichtbaren Anzeigenamen, ein aktuelles Level,
in dem sie sich befindet, und eine Anzahl gesammelter Erfahrungspunkte. Spieler besitzen ein
Inventar mit beliebig vielen Gegenständen.

**Gegenstand** Ein Gegenstand hat einen Namen, einen Typ, eine Effektart und einen Effektwert
(numerisch). Zusätzlich besitzt jeder Gegenstand ein Attribut, das angibt, ob er einzigartig ist.

**Gegner** Ein Gegner hat einen Namen, eine bestimmte Anzahl an Lebenspunkten, eine Angriffsstärke
und einen Typ. Gegner erscheinen in bestimmten Leveln.

**Gegenstandstyp** Es gibt verschiedene Typen von Gegenständen: Waffe, Rüstung, Trank, Schlüssel,
Questgegenstand.

**Effektart** Ein Gegenstand kann verschiedene Effektarten haben: Schaden, Heilung, Verteidigung,
Schlüssel, Quest.

**Gegnertyp** Es gibt verschiedene Gegnertypen: Goblin, Troll, Drache, Untoter, Bandit.

**Schwierigkeitsstufe** Level können eine von vier Schwierigkeitsstufen haben: Leicht, Mittel, Schwer,
Extrem.

In [1]:
# ... euer Code :)

In [3]:
# Benutzt eine Zelle pro Klasse/Enum, um es übersichtlich zu halten

In [5]:
# Wenn ihr noch Zeit und Lust habt, könnt ihr Methoden zu den Klassen hinzufügen.

# Hier ein optionales Beispiel, falls ihr keine Ideen habt:
# - Ein Spieler kann Schaden bekommen. Wenn sie eine Rüstung im Inventar hat, bekommt sie weniger Schaden.

In [19]:
class Game:
    def __init__(self, name, desc, levels):
        self.name = name
        self.description = desc
        self.levels = levels

In [7]:
class Level:
    def __init__(self, number, name, dif, desc, lvl_map, enemies, objects):
        self.number = number
        self.name = name
        self.difficulty = dif
        self.description = desc
        self.map = lvl_map
        self.enemies = enemies
        self.objects = objects

In [12]:
import numpy as np

class Map:
    def __init__(self, width, height):
        self.layout = np.zeros((width, height)) # Liste mit fester Größe Width x Height

print(Map(3, 4).layout) # Bei einem echten Spiel muss dann halt was anderes rein als 0er

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [21]:
class Player:
    def __init__(user_name, display_name, current_level, exp_count):
        self.user_name = user_name
        self.display_name = display_name
        self.current_level = current_level
        self.exp_count = exp_count
        self.inventory = [] # einfach eine Liste mit Gegenständen, wird gefüllt wenn Spieler Gegenstände sammelt
        self.hp = 100 # Für Schaden-Idee
        
    def pickup_object(new_object):
        self.inventory.append(new_object)
        
    def get_damage(damage): # Schaden-Idee
        number_of_armor_in_inventory = 0
        for obj in self.inventory:
            if obj.object_type == ObjectType.ARMOR:
                number_of_armor_in_inventory += 1
        damage /= number_of_armor_in_inventory + 1 # Unverändert wenn keine Rüstung
        
        self.hp -= damage
        
        if self.hp <= 0:
            print(f"Spieler {self.display_name} ist gestorben!")
            self.exp_count = 0
            self.inventory = []

In [14]:
class Object:
    def __init__(self, name, object_type, effect_type, effect_value, is_unique):
        self.name = name
        self.object_type = object_type
        self.effect_type = effect_type
        self.effect_value = effect_value
        self.is_unique = is_unique

In [15]:
class Enemy:
    def __init__(self, name, hp, atk):
        self.name = name
        self.hp = hp
        self.atk = atk
        
class Goblin(Enemy):
    def __init__(self, name):
        super().__init__(name, 100, 15)

class Troll(Enemy):
    def __init__(self, name):
        super().__init__(name, 2000, 50)
        
class Drake(Enemy):
    def __init__(self, name):
        super().__init__(name, 5000, 250)
        
class Undead(Enemy):
    def __init__(self, name):
        super().__init__(name, 150, 30)
        
class Bandit(Enemy):
    def __init__(self, name):
        super().__init__(name, 50, 5)

In [16]:
from enum import Enum
class ObjectType(Enum):
    WEAPON = 1
    ARMOR = 2
    POTION = 3
    KEY = 4
    QUEST_OBJECT = 5

In [17]:
class EffectType(Enum):
    DAMAGE = 1
    HEALING = 2
    DEFENCE = 3
    KEY = 4
    QUEST = 5

In [18]:
class Difficulty(Enum):
    EASY = 1
    MEDIUM = 2
    HARD = 3
    HARDCORE = 4